# Generated by Django 4.2 on 2026-01-23 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Has admin verified documents?'),
        ),
        migrations.AddField(
            model_name='company',
            name='proof_document',
            field=models.FileField(blank=True, help_text='Official registration document (PDF/Image)', null=True, upload_to='company_proofs/'),
        ),
        migrations.AddField(
            model_name='company',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Business Registration No / CIN / GST', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is subscription active?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('platform_admin', 'Platform Super Admin'), ('employer_admin', 'Employer / Company Admin'), ('manager', 'Manager')], default='employer_admin', max_length=20),
        ),
    ]
