# Generated by Django 5.2.10 on 2026-01-20 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('punch_type', models.CharField(choices=[('IN', 'Check In'), ('OUT', 'Check Out')], max_length=3)),
                ('confidence_score', models.FloatField(help_text='Recognition confidence (0-100)')),
                ('face_distance', models.FloatField(help_text='Face encoding distance')),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='attendance_snapshots/')),
                ('is_manual', models.BooleanField(default=False, help_text='Manually marked by admin')),
                ('notes', models.TextField(blank=True, null=True)),
                ('camera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='cameras.camera')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee')),
            ],
            options={
                'db_table': 'attendance_records',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DailyAttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_present', models.BooleanField(default=False)),
                ('is_late', models.BooleanField(default=False)),
                ('is_early_departure', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='employees.employee')),
                ('first_punch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_first_punch', to='attendance.attendancerecord')),
                ('last_punch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_last_punch', to='attendance.attendancerecord')),
            ],
            options={
                'db_table': 'daily_attendance_summary',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['employee', 'timestamp'], name='attendance__employe_4b83af_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['timestamp'], name='attendance__timesta_8c8536_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyattendancesummary',
            index=models.Index(fields=['date'], name='daily_atten_date_f2033c_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyattendancesummary',
            index=models.Index(fields=['employee', 'date'], name='daily_atten_employe_fc78fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyattendancesummary',
            unique_together={('employee', 'date')},
        ),
    ]
